// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVBbSIdQdJ03V52NCyP7NimMairLf9xw0',
    appId: '1:78419364508:web:0f81718075020d1465bb59',
    messagingSenderId: '78419364508',
    projectId: 'fcmoee',
    authDomain: 'fcmoee.firebaseapp.com',
    storageBucket: 'fcmoee.firebasestorage.app',
    measurementId: 'G-6QG768BK8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAit2qMWpBDztr7lQGxPkvnUzBrMozVTRA',
    appId: '1:78419364508:android:305e3129502f6aa065bb59',
    messagingSenderId: '78419364508',
    projectId: 'fcmoee',
    storageBucket: 'fcmoee.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3dORxyyZEny1LUzgUXiDVdW21KtzF2a0',
    appId: '1:78419364508:ios:8d83d3c7cd1ced2c65bb59',
    messagingSenderId: '78419364508',
    projectId: 'fcmoee',
    storageBucket: 'fcmoee.firebasestorage.app',
    iosBundleId: 'com.biolab.checksheet',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3dORxyyZEny1LUzgUXiDVdW21KtzF2a0',
    appId: '1:78419364508:ios:8d83d3c7cd1ced2c65bb59',
    messagingSenderId: '78419364508',
    projectId: 'fcmoee',
    storageBucket: 'fcmoee.firebasestorage.app',
    iosBundleId: 'com.biolab.checksheet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVBbSIdQdJ03V52NCyP7NimMairLf9xw0',
    appId: '1:78419364508:web:50b281eb45fc838c65bb59',
    messagingSenderId: '78419364508',
    projectId: 'fcmoee',
    authDomain: 'fcmoee.firebaseapp.com',
    storageBucket: 'fcmoee.firebasestorage.app',
    measurementId: 'G-ND82WVW7KE',
  );
}
