// lib/data/models/logged_in_user.dart
import 'package:json_annotation/json_annotation.dart';

part 'logged_in_user.g.dart'; // This will be generated by build_runner

// Equivalent to data class LoggedInUser(val userId: String, val displayName: String) in Kotlin
@JsonSerializable()
class LoggedInUser {
  final String userId;
  final String displayName;
  final String userCode; // Added as it seems to be used for login
  final String password; // Added for completeness, if it's part of the user model for internal use

  LoggedInUser({
    required this.userId,
    required this.displayName,
    required this.userCode,
    required this.password,
  });

  factory LoggedInUser.fromJson(Map<String, dynamic> json) => _$LoggedInUserFromJson(json);
  Map<String, dynamic> toJson() => _$LoggedInUserToJson(this);
}